version: "3"
services:
  todo:
    build:
      context: ./
    image: "cypress/cypress-tutorial-build-todo:local"
    container_name: todo
    ports:
      - "3000:3000"
      - "8080:8080"

  cypress:
    image: "cypress/included:6.5.0"
    working_dir: /e2e
    volumes:
      - ./:/e2e
    environment:
      CYPRESS_baseUrl: "http://todo:3000"
      CYPRESS_API_URL: "http://todo:8080"
    depends_on:
      - todo
    links:
      - todo
